---
- name: Prepare system
  import_tasks: prepare.yml

- name: Install NiFi
  import_tasks: install.yml

- name: Customize NiFi
  import_tasks: customize.yml

- name: Add NiFi as system service
  import_tasks: systemd.yml
