---
- name: Prepare system
  become: yes
  import_tasks: prepare.yml
  tags:
  - root

- name: Install NiFi
  import_tasks: install.yml

- name: Customize NiFi
  become: yes
  become_user: "{{ nifi_user }}"
  import_tasks: customize.yml
  tags:
  - root
  - no-root

- name: Add NiFi as system service
  become: yes
  import_tasks: systemd.yml
  tags:
  - root
