---
- name: Copy systemd template
  template:
    src: "templates/nifi.service.j2"
    dest: "/etc/systemd/system/nifi.service"

- name: Enable NiFi service
  service:
    name: nifi
    state: restarted
    daemon_reload: yes
    enabled: yes
