---
- name: Populate service facts
  ansible.builtin.service_facts:

- debug:
    msg: "WARNING: nifi service was not detected, skipping adding handler on restart"
  when: "not ansible_facts.services is defined or not 'nifi' in ansible_facts.services"

- name: restart_nifi
  service:
    name: nifi
    state: restarted
  when: "ansible_facts.services is defined and 'nifi' in ansible_facts.services"
